version: "3.8"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: golook
      POSTGRES_USER: golook
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./migrations/init_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql